services:
  traefik:
    image: traefik:v2.11
    container_name: traefik
    command:
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
      - "--api.dashboard=true"
    ports:
      - "80:80"
    networks:
      - appnet
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      
  neo4j:
    image: neo4j:5.22.0-community
    container_name: neo4j_db
    restart: always
    environment:
      NEO4J_AUTH: "${NEO4J_USER}/${NEO4J_PASSWORD}"
    volumes:
      - neo4j_data:/data
    ports:
      - firstnet
      

  backend_flask:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: flask_backend
    restart: always
    depends_on:
      - neo4j
    env_file:
      - .env
    ports:
      - firstnet

volumes:
  neo4j_data:
    driver: local
    
networks:
  firstnet:
    driver: bridge
    
