services:
  neo4j:
    image: neo4j:5.22.0-community
    container_name: neo4j_db
    restart: always
    environment:
      NEO4J_AUTH: "${NEO4J_USER}/${NEO4J_PASSWORD}"
    ports:
      - "7474:7474"
      - "7687:7687"
    volumes:
      - neo4j_data:/data

  backend_flask:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: flask_backend
    restart: always
    depends_on:
      - neo4j
    env_file:
      - .env
    ports:
      - "${FLASK_PORT:-5000}:5000"

volumes:
  neo4j_data:
    driver: local